Mohistmc
pelican-eggs/minecraft pull request #33
Opened 2024-10-09 21:25 UTC by cocorico8

# Description

## Checklist for all submissions

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you tested and reviewed your changes with confidence that everything works?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
* [x] You verify that the start command applied does not use a shell script
* [x] The egg was exported from the panel

Ok so I know there is already a PR for this one, but mine is refactored for the install script, I based it on the paper install script so it's cleaner, i also added the possibility to install the fabric version of mohist (banner), also added java 21. In this PR I also fixed the proxy readme as it was not pointing to the right place and added the fact that windows 11 is a thing.

2024-10-20 18:29 UTC, QuintenQVD0 requested changes

2024-10-20 18:29 UTC, QuintenQVD0 commented on java/mohist/egg-mohist.json
> +    "startup": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}",
No, this is wrong.

Keep the 95 logic as it send 95% of the allocated ram to the server and works with unlimited (0)

2024-10-20 18:29 UTC, QuintenQVD0 commented on java/mohist/egg-mohist.json
> +            "env_variable": "MINECRAFT_VERSION",
You should never edit the env variable, keep it as is

2024-10-20 18:51 UTC, cocorico8 commented on java/mohist/egg-mohist.json
> +            "env_variable": "MINECRAFT_VERSION",
updated

2024-10-20 18:51 UTC, cocorico8 commented on java/mohist/egg-mohist.json
> +    "startup": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}",
updated

2024-11-02 08:51 UTC, QuintenQVD0 approved these changes
LGTM! thanks

2024-11-02 08:52 UTC, merged